name: Docker Build & Push

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  DOCKER_USERNAME: arkshocer
  DOCKER_CONTAINER_NAME: caddy-docker-azuredns
  DOCKER_TARGET_PLATFORM: linux/amd64, linux/arm64, linux/arm/v8, linux/arm/v7
  GITHUB_REGISTRY_ORG_NAME: arkshocer

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base_image: caddy:2.8.4-builder
            final_image: caddy:2.8.4
          - base_image: caddy:2.8.4-builder-alpine
            final_image: caddy:2.8.4-alpine
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: success()
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
            FINAL_IMAGE=${{ matrix.final_image }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ matrix.base_image }}
          labels: ${{ steps.meta.outputs.labels }}